services:
  laravel_template:
    image: ghcr.io/alexjonker/laravel_template:main
    container_name: laravel_template
    restart: unless-stopped
    ports:
      - 67:80
    volumes:
      - /DATA/AppData/laravel_template/app:/laravel_template-data
      - /DATA/AppData/laravel_template/logs:/var/www/html/storage/logs
    environment:
      - APP_NAME=laravel_template
      - APP_URL=http://localhost:67
      - TIMEZONE=Europe/Amsterdam

      # Database
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=laravel_template
      - DB_USERNAME=laravel_template
      - DB_PASSWORD=ifcLwRI0SrBaDMs9lPTsCHQqF4NmMnHaXGWsYtQuu8wvSZWMfw99CoKqPjGkH9KIx1v
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "/bin/sh", "/healthcheck.sh"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
  db:
    image: mariadb:latest
    container_name: laravel_template-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=laravel_template
      - MYSQL_USER=laravel_template
      - MYSQL_PASSWORD=ifcLwRI0SrBaDMs9lPTsCHQqF4NmMnHaXGWsYtQuu8wvSZWMfw99CoKqPjGkH9KIx1v
      - MYSQL_ROOT_PASSWORD=do_not_change_this_without_also_changing_healthcheck_VlECtVfW07GqKtwh6qE42fSPBb43NRcrNyCuB5N3QNJHSRzsvuAIgn9uohWBnUgdZDX
    volumes:
      - /DATA/AppData/laravel_template/db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin" ,"ping", "-h", "localhost", "--password=do_not_change_this_without_also_changing_healthcheck_VlECtVfW07GqKtwh6qE42fSPBb43NRcrNyCuB5N3QNJHSRzsvuAIgn9uohWBnUgdZDX"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
networks: {}